import './global.css';
import Script from 'next/script';

export const metadata = {
  title: 'Welcome to next',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <Script src="https://cdn.tailwindcss.com"></Script>
      </head>
      <body>
        <div className="container mx-auto px-4">{children}</div>
      </body>
    </html>
  );
}
